### ISSUE TITLE
Attached logs of solr.aclTracker error. 

### ISSUE THREAD

**Issue by DBlamire** [Open-MBEE/mms-alfresco#106]
The current setup that the server is using.
RHEL 6.6
Tomcat 7.0.78
Alfresco Community 5.0.d
ActiveMQ 5.14.5
Elasticsearch 5.4.1
PostgresQL-9.3
Issue after installing the amps to war files and running alfresco

[Logs.txt](https://github.com/Open-MBEE/mms/files/1166243/Logs.txt)

ERROR [solr.tracker.AclTracker] [SolrTrackerScheduler_Worker-3] First acl transaction was not found with the correct timestamp.
2017-07-19 11:15:00,106  ERROR [solr.tracker.AclTracker] [SolrTrackerScheduler_Worker-2] First acl transaction was not found with the correct timestamp.
 2017-07-19 11:15:00,106  ERROR [solr.tracker.AclTracker] [SolrTrackerScheduler_Worker-2] SOLR has successfully connected to your repository  however the SOLR indexes and repository database do not match.

**Comment by DBlamire** [comment]
We have given up on this server and have moved to starting again on a RHEL 6.9 installation. 
Is there a difference in the scripting for a CENTOS 6/ RHEL6 installation or any difference from 6.7 to 6.9?

Very Respectfully,
David

**Comment by HuiJun** [comment]
Hi David,

With 5.0.d, on starting up, catalina will start up before solr is able to read configurations. This usually results in about 3 individual 403 errors by solr. However, this doesn't seem to be the case here. According to the logs, it looks like a solr reindex is needed. This usually happens when the data in solr4 does not match the data in alf_data or in alfresco's database, or solr4 is unable to write to the directory that it is configured to write to. Please reopen the issue if this continues to be a problem.
